---
- import_tasks: choose_master.yml
  when:
    - rabbitmq_cluster_node

# - import_tasks: set_resolve_peers.yml
#   when:
#     - rabbitmq_resolve_peers | length == 0
#     - rabbitmq_cluster_node
#     - (rabbitmq_cluster_info is undefined) or (ansible_hostname == rabbitmq_master_node)
#     - inventory_hostname not in rabbitmq_installed_nodes_list | default([])

- name: Get RABBITMQ_CLUSTER_NODE_NAME
  set_fact:
    rabbitmq_cluster_node_name: "{{ (rabbitmq_container_info.container.Config.Env | map('split', '=', 1) | community.general.dict).RABBITMQ_CLUSTER_NODE_NAME }}"
  ignore_errors: true
  when: inventory_hostname in rabbitmq_running_nodes_list | default([])

- name: Set RABBITMQ_CLUSTER_NODE_NAME for new nodes
  set_fact:
    rabbitmq_cluster_node_name: rabbit@{{ hostvars[rabbitmq_master_node].rabbitmq_hostname | default(hostvars[rabbitmq_master_node].ansible_facts.hostname) }}
  when:
    - rabbitmq_master_node is defined
    - rabbitmq_master_node != inventory_hostname
    - inventory_hostname not in rabbitmq_running_nodes_list | default([])

- name: Run rabbitmq master
  import_tasks: run_container.yml
  when:
    - rabbitmq_master_node | default("") == inventory_hostname

- name: Wait while master is running
  community.docker.docker_container_info:
    name: "{{ rabbitmq_container_name }}"
  register: rabbitmq_health_status
  retries: 10
  delay: 10
  until: rabbitmq_health_status.container.State.Health.Status == "healthy"
  when: rabbitmq_master_node | default("") == inventory_hostname

- name: Run rabbitmq
  import_tasks: run_container.yml
  when:
    - rabbitmq_master_node | default("") != inventory_hostname
