---
- name: Run container {{ rabbitmq_container_name }}
  community.docker.docker_compose_v2:
    state: present
    project_name: rabbitmq
    definition:
      volumes:
        rabbitmq_data:
      services:
        rabbitmq:
          image: "{{ rabbitmq_image_name }}"
          container_name: "{{ rabbitmq_container_name }}"
          hostname: "{{ rabbitmq_hostname }}"
          restart: unless-stopped
          environment: "{{ rabbitmq_export_vars }}"
          volumes:
            - "{{ rabbitmq_data }}:/bitnami/rabbitmq/mnesia"
          ports: "{{ rabbitmq_expose_ports }}"
          extra_hosts: "{{ rabbitmq_resolve_peers }}"
          healthcheck:
            test: rabbitmqctl status
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 10s
